framework:
    cache:
        pools:
            redis_cache:
                adapter: cache.adapter.redis
                provider: '%env(REDIS)%'

        # App cache
        app: cache.adapter.redis

        # System cache
        system: cache.adapter.redis

        default_redis_provider: '%env(REDIS)%'
