framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(RABBITMQ_DSN)%'
                options:
                    queues:
                        download_queue: ~

            failed:
                dsn: '%env(RABBITMQ_DSN)%'
                options:
                    queues:
                        failed_queue: ~

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction

        routing:
            App\Message\DownloadMessage: async
